/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TSlugRouteImport } from './routes/t.$slug'
import { Route as AuthSignupRouteImport } from './routes/auth.signup'
import { Route as AuthResetPasswordRouteImport } from './routes/auth.reset-password'
import { Route as AuthLoginRouteImport } from './routes/auth.login'
import { Route as AuthForgotPasswordRouteImport } from './routes/auth.forgot-password'
import { Route as TSlugIndexRouteImport } from './routes/t.$slug.index'
import { Route as TSlugSuppliersRouteImport } from './routes/t.$slug.suppliers'
import { Route as TSlugSettingsRouteImport } from './routes/t.$slug.settings'
import { Route as TSlugSalesRouteImport } from './routes/t.$slug.sales'
import { Route as TSlugReceiptsRouteImport } from './routes/t.$slug.receipts'
import { Route as TSlugProductsRouteImport } from './routes/t.$slug.products'
import { Route as TSlugPosRouteImport } from './routes/t.$slug.pos'
import { Route as TSlugInsightsRouteImport } from './routes/t.$slug.insights'
import { Route as TSlugEmployeesRouteImport } from './routes/t.$slug.employees'
import { Route as TSlugCustomersRouteImport } from './routes/t.$slug.customers'
import { Route as TSlugCreditLedgerRouteImport } from './routes/t.$slug.credit-ledger'

const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TSlugRoute = TSlugRouteImport.update({
  id: '/t/$slug',
  path: '/t/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/auth/signup',
  path: '/auth/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/auth/reset-password',
  path: '/auth/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/auth/forgot-password',
  path: '/auth/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const TSlugIndexRoute = TSlugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TSlugRoute,
} as any)
const TSlugSuppliersRoute = TSlugSuppliersRouteImport.update({
  id: '/suppliers',
  path: '/suppliers',
  getParentRoute: () => TSlugRoute,
} as any)
const TSlugSettingsRoute = TSlugSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => TSlugRoute,
} as any)
const TSlugSalesRoute = TSlugSalesRouteImport.update({
  id: '/sales',
  path: '/sales',
  getParentRoute: () => TSlugRoute,
} as any)
const TSlugReceiptsRoute = TSlugReceiptsRouteImport.update({
  id: '/receipts',
  path: '/receipts',
  getParentRoute: () => TSlugRoute,
} as any)
const TSlugProductsRoute = TSlugProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => TSlugRoute,
} as any)
const TSlugPosRoute = TSlugPosRouteImport.update({
  id: '/pos',
  path: '/pos',
  getParentRoute: () => TSlugRoute,
} as any)
const TSlugInsightsRoute = TSlugInsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => TSlugRoute,
} as any)
const TSlugEmployeesRoute = TSlugEmployeesRouteImport.update({
  id: '/employees',
  path: '/employees',
  getParentRoute: () => TSlugRoute,
} as any)
const TSlugCustomersRoute = TSlugCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => TSlugRoute,
} as any)
const TSlugCreditLedgerRoute = TSlugCreditLedgerRouteImport.update({
  id: '/credit-ledger',
  path: '/credit-ledger',
  getParentRoute: () => TSlugRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/onboarding': typeof OnboardingRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/signup': typeof AuthSignupRoute
  '/t/$slug': typeof TSlugRouteWithChildren
  '/t/$slug/credit-ledger': typeof TSlugCreditLedgerRoute
  '/t/$slug/customers': typeof TSlugCustomersRoute
  '/t/$slug/employees': typeof TSlugEmployeesRoute
  '/t/$slug/insights': typeof TSlugInsightsRoute
  '/t/$slug/pos': typeof TSlugPosRoute
  '/t/$slug/products': typeof TSlugProductsRoute
  '/t/$slug/receipts': typeof TSlugReceiptsRoute
  '/t/$slug/sales': typeof TSlugSalesRoute
  '/t/$slug/settings': typeof TSlugSettingsRoute
  '/t/$slug/suppliers': typeof TSlugSuppliersRoute
  '/t/$slug/': typeof TSlugIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/onboarding': typeof OnboardingRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/signup': typeof AuthSignupRoute
  '/t/$slug/credit-ledger': typeof TSlugCreditLedgerRoute
  '/t/$slug/customers': typeof TSlugCustomersRoute
  '/t/$slug/employees': typeof TSlugEmployeesRoute
  '/t/$slug/insights': typeof TSlugInsightsRoute
  '/t/$slug/pos': typeof TSlugPosRoute
  '/t/$slug/products': typeof TSlugProductsRoute
  '/t/$slug/receipts': typeof TSlugReceiptsRoute
  '/t/$slug/sales': typeof TSlugSalesRoute
  '/t/$slug/settings': typeof TSlugSettingsRoute
  '/t/$slug/suppliers': typeof TSlugSuppliersRoute
  '/t/$slug': typeof TSlugIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/onboarding': typeof OnboardingRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/signup': typeof AuthSignupRoute
  '/t/$slug': typeof TSlugRouteWithChildren
  '/t/$slug/credit-ledger': typeof TSlugCreditLedgerRoute
  '/t/$slug/customers': typeof TSlugCustomersRoute
  '/t/$slug/employees': typeof TSlugEmployeesRoute
  '/t/$slug/insights': typeof TSlugInsightsRoute
  '/t/$slug/pos': typeof TSlugPosRoute
  '/t/$slug/products': typeof TSlugProductsRoute
  '/t/$slug/receipts': typeof TSlugReceiptsRoute
  '/t/$slug/sales': typeof TSlugSalesRoute
  '/t/$slug/settings': typeof TSlugSettingsRoute
  '/t/$slug/suppliers': typeof TSlugSuppliersRoute
  '/t/$slug/': typeof TSlugIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/onboarding'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/reset-password'
    | '/auth/signup'
    | '/t/$slug'
    | '/t/$slug/credit-ledger'
    | '/t/$slug/customers'
    | '/t/$slug/employees'
    | '/t/$slug/insights'
    | '/t/$slug/pos'
    | '/t/$slug/products'
    | '/t/$slug/receipts'
    | '/t/$slug/sales'
    | '/t/$slug/settings'
    | '/t/$slug/suppliers'
    | '/t/$slug/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/onboarding'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/reset-password'
    | '/auth/signup'
    | '/t/$slug/credit-ledger'
    | '/t/$slug/customers'
    | '/t/$slug/employees'
    | '/t/$slug/insights'
    | '/t/$slug/pos'
    | '/t/$slug/products'
    | '/t/$slug/receipts'
    | '/t/$slug/sales'
    | '/t/$slug/settings'
    | '/t/$slug/suppliers'
    | '/t/$slug'
  id:
    | '__root__'
    | '/'
    | '/onboarding'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/reset-password'
    | '/auth/signup'
    | '/t/$slug'
    | '/t/$slug/credit-ledger'
    | '/t/$slug/customers'
    | '/t/$slug/employees'
    | '/t/$slug/insights'
    | '/t/$slug/pos'
    | '/t/$slug/products'
    | '/t/$slug/receipts'
    | '/t/$slug/sales'
    | '/t/$slug/settings'
    | '/t/$slug/suppliers'
    | '/t/$slug/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  OnboardingRoute: typeof OnboardingRoute
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
  AuthSignupRoute: typeof AuthSignupRoute
  TSlugRoute: typeof TSlugRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/t/$slug': {
      id: '/t/$slug'
      path: '/t/$slug'
      fullPath: '/t/$slug'
      preLoaderRoute: typeof TSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/signup': {
      id: '/auth/signup'
      path: '/auth/signup'
      fullPath: '/auth/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/reset-password': {
      id: '/auth/reset-password'
      path: '/auth/reset-password'
      fullPath: '/auth/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/forgot-password': {
      id: '/auth/forgot-password'
      path: '/auth/forgot-password'
      fullPath: '/auth/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/t/$slug/': {
      id: '/t/$slug/'
      path: '/'
      fullPath: '/t/$slug/'
      preLoaderRoute: typeof TSlugIndexRouteImport
      parentRoute: typeof TSlugRoute
    }
    '/t/$slug/suppliers': {
      id: '/t/$slug/suppliers'
      path: '/suppliers'
      fullPath: '/t/$slug/suppliers'
      preLoaderRoute: typeof TSlugSuppliersRouteImport
      parentRoute: typeof TSlugRoute
    }
    '/t/$slug/settings': {
      id: '/t/$slug/settings'
      path: '/settings'
      fullPath: '/t/$slug/settings'
      preLoaderRoute: typeof TSlugSettingsRouteImport
      parentRoute: typeof TSlugRoute
    }
    '/t/$slug/sales': {
      id: '/t/$slug/sales'
      path: '/sales'
      fullPath: '/t/$slug/sales'
      preLoaderRoute: typeof TSlugSalesRouteImport
      parentRoute: typeof TSlugRoute
    }
    '/t/$slug/receipts': {
      id: '/t/$slug/receipts'
      path: '/receipts'
      fullPath: '/t/$slug/receipts'
      preLoaderRoute: typeof TSlugReceiptsRouteImport
      parentRoute: typeof TSlugRoute
    }
    '/t/$slug/products': {
      id: '/t/$slug/products'
      path: '/products'
      fullPath: '/t/$slug/products'
      preLoaderRoute: typeof TSlugProductsRouteImport
      parentRoute: typeof TSlugRoute
    }
    '/t/$slug/pos': {
      id: '/t/$slug/pos'
      path: '/pos'
      fullPath: '/t/$slug/pos'
      preLoaderRoute: typeof TSlugPosRouteImport
      parentRoute: typeof TSlugRoute
    }
    '/t/$slug/insights': {
      id: '/t/$slug/insights'
      path: '/insights'
      fullPath: '/t/$slug/insights'
      preLoaderRoute: typeof TSlugInsightsRouteImport
      parentRoute: typeof TSlugRoute
    }
    '/t/$slug/employees': {
      id: '/t/$slug/employees'
      path: '/employees'
      fullPath: '/t/$slug/employees'
      preLoaderRoute: typeof TSlugEmployeesRouteImport
      parentRoute: typeof TSlugRoute
    }
    '/t/$slug/customers': {
      id: '/t/$slug/customers'
      path: '/customers'
      fullPath: '/t/$slug/customers'
      preLoaderRoute: typeof TSlugCustomersRouteImport
      parentRoute: typeof TSlugRoute
    }
    '/t/$slug/credit-ledger': {
      id: '/t/$slug/credit-ledger'
      path: '/credit-ledger'
      fullPath: '/t/$slug/credit-ledger'
      preLoaderRoute: typeof TSlugCreditLedgerRouteImport
      parentRoute: typeof TSlugRoute
    }
  }
}

interface TSlugRouteChildren {
  TSlugCreditLedgerRoute: typeof TSlugCreditLedgerRoute
  TSlugCustomersRoute: typeof TSlugCustomersRoute
  TSlugEmployeesRoute: typeof TSlugEmployeesRoute
  TSlugInsightsRoute: typeof TSlugInsightsRoute
  TSlugPosRoute: typeof TSlugPosRoute
  TSlugProductsRoute: typeof TSlugProductsRoute
  TSlugReceiptsRoute: typeof TSlugReceiptsRoute
  TSlugSalesRoute: typeof TSlugSalesRoute
  TSlugSettingsRoute: typeof TSlugSettingsRoute
  TSlugSuppliersRoute: typeof TSlugSuppliersRoute
  TSlugIndexRoute: typeof TSlugIndexRoute
}

const TSlugRouteChildren: TSlugRouteChildren = {
  TSlugCreditLedgerRoute: TSlugCreditLedgerRoute,
  TSlugCustomersRoute: TSlugCustomersRoute,
  TSlugEmployeesRoute: TSlugEmployeesRoute,
  TSlugInsightsRoute: TSlugInsightsRoute,
  TSlugPosRoute: TSlugPosRoute,
  TSlugProductsRoute: TSlugProductsRoute,
  TSlugReceiptsRoute: TSlugReceiptsRoute,
  TSlugSalesRoute: TSlugSalesRoute,
  TSlugSettingsRoute: TSlugSettingsRoute,
  TSlugSuppliersRoute: TSlugSuppliersRoute,
  TSlugIndexRoute: TSlugIndexRoute,
}

const TSlugRouteWithChildren = TSlugRoute._addFileChildren(TSlugRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  OnboardingRoute: OnboardingRoute,
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
  AuthSignupRoute: AuthSignupRoute,
  TSlugRoute: TSlugRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
