/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TSlugRouteImport } from './routes/t.$slug'
import { Route as AuthSignupRouteImport } from './routes/auth.signup'
import { Route as AuthResetPasswordRouteImport } from './routes/auth.reset-password'
import { Route as AuthLoginRouteImport } from './routes/auth.login'
import { Route as AuthForgotPasswordRouteImport } from './routes/auth.forgot-password'
import { Route as TSlugIndexRouteImport } from './routes/t.$slug.index'
import { Route as TSlugSuppliersRouteImport } from './routes/t.$slug.suppliers'
import { Route as TSlugStoresRouteImport } from './routes/t.$slug.stores'
import { Route as TSlugSettingsRouteImport } from './routes/t.$slug.settings'
import { Route as TSlugSalesRouteImport } from './routes/t.$slug.sales'
import { Route as TSlugRolesPermissionsRouteImport } from './routes/t.$slug.roles-permissions'
import { Route as TSlugReceiptsRouteImport } from './routes/t.$slug.receipts'
import { Route as TSlugPurchaseOrdersRouteImport } from './routes/t.$slug.purchase-orders'
import { Route as TSlugPosRouteImport } from './routes/t.$slug.pos'
import { Route as TSlugPackageRouteImport } from './routes/t.$slug.package'
import { Route as TSlugOfflineModeRouteImport } from './routes/t.$slug.offline-mode'
import { Route as TSlugNotificationsRouteImport } from './routes/t.$slug.notifications'
import { Route as TSlugInsightsRouteImport } from './routes/t.$slug.insights'
import { Route as TSlugEmployeesRouteImport } from './routes/t.$slug.employees'
import { Route as TSlugCustomersRouteImport } from './routes/t.$slug.customers'
import { Route as TSlugCreditLedgerRouteImport } from './routes/t.$slug.credit-ledger'
import { Route as TSlugProductsIndexRouteImport } from './routes/t.$slug.products.index'
import { Route as TSlugProductsStoreIdRouteImport } from './routes/t.$slug.products.$storeId'
import { Route as TSlugFeaturesFeatureKeyRouteImport } from './routes/t.$slug.features.$featureKey'

const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TSlugRoute = TSlugRouteImport.update({
  id: '/t/$slug',
  path: '/t/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/auth/signup',
  path: '/auth/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/auth/reset-password',
  path: '/auth/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/auth/forgot-password',
  path: '/auth/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const TSlugIndexRoute = TSlugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TSlugRoute,
} as any)
const TSlugSuppliersRoute = TSlugSuppliersRouteImport.update({
  id: '/suppliers',
  path: '/suppliers',
  getParentRoute: () => TSlugRoute,
} as any)
const TSlugStoresRoute = TSlugStoresRouteImport.update({
  id: '/stores',
  path: '/stores',
  getParentRoute: () => TSlugRoute,
} as any)
const TSlugSettingsRoute = TSlugSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => TSlugRoute,
} as any)
const TSlugSalesRoute = TSlugSalesRouteImport.update({
  id: '/sales',
  path: '/sales',
  getParentRoute: () => TSlugRoute,
} as any)
const TSlugRolesPermissionsRoute = TSlugRolesPermissionsRouteImport.update({
  id: '/roles-permissions',
  path: '/roles-permissions',
  getParentRoute: () => TSlugRoute,
} as any)
const TSlugReceiptsRoute = TSlugReceiptsRouteImport.update({
  id: '/receipts',
  path: '/receipts',
  getParentRoute: () => TSlugRoute,
} as any)
const TSlugPurchaseOrdersRoute = TSlugPurchaseOrdersRouteImport.update({
  id: '/purchase-orders',
  path: '/purchase-orders',
  getParentRoute: () => TSlugRoute,
} as any)
const TSlugPosRoute = TSlugPosRouteImport.update({
  id: '/pos',
  path: '/pos',
  getParentRoute: () => TSlugRoute,
} as any)
const TSlugPackageRoute = TSlugPackageRouteImport.update({
  id: '/package',
  path: '/package',
  getParentRoute: () => TSlugRoute,
} as any)
const TSlugOfflineModeRoute = TSlugOfflineModeRouteImport.update({
  id: '/offline-mode',
  path: '/offline-mode',
  getParentRoute: () => TSlugRoute,
} as any)
const TSlugNotificationsRoute = TSlugNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => TSlugRoute,
} as any)
const TSlugInsightsRoute = TSlugInsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => TSlugRoute,
} as any)
const TSlugEmployeesRoute = TSlugEmployeesRouteImport.update({
  id: '/employees',
  path: '/employees',
  getParentRoute: () => TSlugRoute,
} as any)
const TSlugCustomersRoute = TSlugCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => TSlugRoute,
} as any)
const TSlugCreditLedgerRoute = TSlugCreditLedgerRouteImport.update({
  id: '/credit-ledger',
  path: '/credit-ledger',
  getParentRoute: () => TSlugRoute,
} as any)
const TSlugProductsIndexRoute = TSlugProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => TSlugRoute,
} as any)
const TSlugProductsStoreIdRoute = TSlugProductsStoreIdRouteImport.update({
  id: '/products/$storeId',
  path: '/products/$storeId',
  getParentRoute: () => TSlugRoute,
} as any)
const TSlugFeaturesFeatureKeyRoute = TSlugFeaturesFeatureKeyRouteImport.update({
  id: '/features/$featureKey',
  path: '/features/$featureKey',
  getParentRoute: () => TSlugRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/onboarding': typeof OnboardingRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/signup': typeof AuthSignupRoute
  '/t/$slug': typeof TSlugRouteWithChildren
  '/t/$slug/credit-ledger': typeof TSlugCreditLedgerRoute
  '/t/$slug/customers': typeof TSlugCustomersRoute
  '/t/$slug/employees': typeof TSlugEmployeesRoute
  '/t/$slug/insights': typeof TSlugInsightsRoute
  '/t/$slug/notifications': typeof TSlugNotificationsRoute
  '/t/$slug/offline-mode': typeof TSlugOfflineModeRoute
  '/t/$slug/package': typeof TSlugPackageRoute
  '/t/$slug/pos': typeof TSlugPosRoute
  '/t/$slug/purchase-orders': typeof TSlugPurchaseOrdersRoute
  '/t/$slug/receipts': typeof TSlugReceiptsRoute
  '/t/$slug/roles-permissions': typeof TSlugRolesPermissionsRoute
  '/t/$slug/sales': typeof TSlugSalesRoute
  '/t/$slug/settings': typeof TSlugSettingsRoute
  '/t/$slug/stores': typeof TSlugStoresRoute
  '/t/$slug/suppliers': typeof TSlugSuppliersRoute
  '/t/$slug/': typeof TSlugIndexRoute
  '/t/$slug/features/$featureKey': typeof TSlugFeaturesFeatureKeyRoute
  '/t/$slug/products/$storeId': typeof TSlugProductsStoreIdRoute
  '/t/$slug/products/': typeof TSlugProductsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/onboarding': typeof OnboardingRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/signup': typeof AuthSignupRoute
  '/t/$slug/credit-ledger': typeof TSlugCreditLedgerRoute
  '/t/$slug/customers': typeof TSlugCustomersRoute
  '/t/$slug/employees': typeof TSlugEmployeesRoute
  '/t/$slug/insights': typeof TSlugInsightsRoute
  '/t/$slug/notifications': typeof TSlugNotificationsRoute
  '/t/$slug/offline-mode': typeof TSlugOfflineModeRoute
  '/t/$slug/package': typeof TSlugPackageRoute
  '/t/$slug/pos': typeof TSlugPosRoute
  '/t/$slug/purchase-orders': typeof TSlugPurchaseOrdersRoute
  '/t/$slug/receipts': typeof TSlugReceiptsRoute
  '/t/$slug/roles-permissions': typeof TSlugRolesPermissionsRoute
  '/t/$slug/sales': typeof TSlugSalesRoute
  '/t/$slug/settings': typeof TSlugSettingsRoute
  '/t/$slug/stores': typeof TSlugStoresRoute
  '/t/$slug/suppliers': typeof TSlugSuppliersRoute
  '/t/$slug': typeof TSlugIndexRoute
  '/t/$slug/features/$featureKey': typeof TSlugFeaturesFeatureKeyRoute
  '/t/$slug/products/$storeId': typeof TSlugProductsStoreIdRoute
  '/t/$slug/products': typeof TSlugProductsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/onboarding': typeof OnboardingRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/signup': typeof AuthSignupRoute
  '/t/$slug': typeof TSlugRouteWithChildren
  '/t/$slug/credit-ledger': typeof TSlugCreditLedgerRoute
  '/t/$slug/customers': typeof TSlugCustomersRoute
  '/t/$slug/employees': typeof TSlugEmployeesRoute
  '/t/$slug/insights': typeof TSlugInsightsRoute
  '/t/$slug/notifications': typeof TSlugNotificationsRoute
  '/t/$slug/offline-mode': typeof TSlugOfflineModeRoute
  '/t/$slug/package': typeof TSlugPackageRoute
  '/t/$slug/pos': typeof TSlugPosRoute
  '/t/$slug/purchase-orders': typeof TSlugPurchaseOrdersRoute
  '/t/$slug/receipts': typeof TSlugReceiptsRoute
  '/t/$slug/roles-permissions': typeof TSlugRolesPermissionsRoute
  '/t/$slug/sales': typeof TSlugSalesRoute
  '/t/$slug/settings': typeof TSlugSettingsRoute
  '/t/$slug/stores': typeof TSlugStoresRoute
  '/t/$slug/suppliers': typeof TSlugSuppliersRoute
  '/t/$slug/': typeof TSlugIndexRoute
  '/t/$slug/features/$featureKey': typeof TSlugFeaturesFeatureKeyRoute
  '/t/$slug/products/$storeId': typeof TSlugProductsStoreIdRoute
  '/t/$slug/products/': typeof TSlugProductsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/onboarding'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/reset-password'
    | '/auth/signup'
    | '/t/$slug'
    | '/t/$slug/credit-ledger'
    | '/t/$slug/customers'
    | '/t/$slug/employees'
    | '/t/$slug/insights'
    | '/t/$slug/notifications'
    | '/t/$slug/offline-mode'
    | '/t/$slug/package'
    | '/t/$slug/pos'
    | '/t/$slug/purchase-orders'
    | '/t/$slug/receipts'
    | '/t/$slug/roles-permissions'
    | '/t/$slug/sales'
    | '/t/$slug/settings'
    | '/t/$slug/stores'
    | '/t/$slug/suppliers'
    | '/t/$slug/'
    | '/t/$slug/features/$featureKey'
    | '/t/$slug/products/$storeId'
    | '/t/$slug/products/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/onboarding'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/reset-password'
    | '/auth/signup'
    | '/t/$slug/credit-ledger'
    | '/t/$slug/customers'
    | '/t/$slug/employees'
    | '/t/$slug/insights'
    | '/t/$slug/notifications'
    | '/t/$slug/offline-mode'
    | '/t/$slug/package'
    | '/t/$slug/pos'
    | '/t/$slug/purchase-orders'
    | '/t/$slug/receipts'
    | '/t/$slug/roles-permissions'
    | '/t/$slug/sales'
    | '/t/$slug/settings'
    | '/t/$slug/stores'
    | '/t/$slug/suppliers'
    | '/t/$slug'
    | '/t/$slug/features/$featureKey'
    | '/t/$slug/products/$storeId'
    | '/t/$slug/products'
  id:
    | '__root__'
    | '/'
    | '/onboarding'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/reset-password'
    | '/auth/signup'
    | '/t/$slug'
    | '/t/$slug/credit-ledger'
    | '/t/$slug/customers'
    | '/t/$slug/employees'
    | '/t/$slug/insights'
    | '/t/$slug/notifications'
    | '/t/$slug/offline-mode'
    | '/t/$slug/package'
    | '/t/$slug/pos'
    | '/t/$slug/purchase-orders'
    | '/t/$slug/receipts'
    | '/t/$slug/roles-permissions'
    | '/t/$slug/sales'
    | '/t/$slug/settings'
    | '/t/$slug/stores'
    | '/t/$slug/suppliers'
    | '/t/$slug/'
    | '/t/$slug/features/$featureKey'
    | '/t/$slug/products/$storeId'
    | '/t/$slug/products/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  OnboardingRoute: typeof OnboardingRoute
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
  AuthSignupRoute: typeof AuthSignupRoute
  TSlugRoute: typeof TSlugRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/t/$slug': {
      id: '/t/$slug'
      path: '/t/$slug'
      fullPath: '/t/$slug'
      preLoaderRoute: typeof TSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/signup': {
      id: '/auth/signup'
      path: '/auth/signup'
      fullPath: '/auth/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/reset-password': {
      id: '/auth/reset-password'
      path: '/auth/reset-password'
      fullPath: '/auth/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/forgot-password': {
      id: '/auth/forgot-password'
      path: '/auth/forgot-password'
      fullPath: '/auth/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/t/$slug/': {
      id: '/t/$slug/'
      path: '/'
      fullPath: '/t/$slug/'
      preLoaderRoute: typeof TSlugIndexRouteImport
      parentRoute: typeof TSlugRoute
    }
    '/t/$slug/suppliers': {
      id: '/t/$slug/suppliers'
      path: '/suppliers'
      fullPath: '/t/$slug/suppliers'
      preLoaderRoute: typeof TSlugSuppliersRouteImport
      parentRoute: typeof TSlugRoute
    }
    '/t/$slug/stores': {
      id: '/t/$slug/stores'
      path: '/stores'
      fullPath: '/t/$slug/stores'
      preLoaderRoute: typeof TSlugStoresRouteImport
      parentRoute: typeof TSlugRoute
    }
    '/t/$slug/settings': {
      id: '/t/$slug/settings'
      path: '/settings'
      fullPath: '/t/$slug/settings'
      preLoaderRoute: typeof TSlugSettingsRouteImport
      parentRoute: typeof TSlugRoute
    }
    '/t/$slug/sales': {
      id: '/t/$slug/sales'
      path: '/sales'
      fullPath: '/t/$slug/sales'
      preLoaderRoute: typeof TSlugSalesRouteImport
      parentRoute: typeof TSlugRoute
    }
    '/t/$slug/roles-permissions': {
      id: '/t/$slug/roles-permissions'
      path: '/roles-permissions'
      fullPath: '/t/$slug/roles-permissions'
      preLoaderRoute: typeof TSlugRolesPermissionsRouteImport
      parentRoute: typeof TSlugRoute
    }
    '/t/$slug/receipts': {
      id: '/t/$slug/receipts'
      path: '/receipts'
      fullPath: '/t/$slug/receipts'
      preLoaderRoute: typeof TSlugReceiptsRouteImport
      parentRoute: typeof TSlugRoute
    }
    '/t/$slug/purchase-orders': {
      id: '/t/$slug/purchase-orders'
      path: '/purchase-orders'
      fullPath: '/t/$slug/purchase-orders'
      preLoaderRoute: typeof TSlugPurchaseOrdersRouteImport
      parentRoute: typeof TSlugRoute
    }
    '/t/$slug/pos': {
      id: '/t/$slug/pos'
      path: '/pos'
      fullPath: '/t/$slug/pos'
      preLoaderRoute: typeof TSlugPosRouteImport
      parentRoute: typeof TSlugRoute
    }
    '/t/$slug/package': {
      id: '/t/$slug/package'
      path: '/package'
      fullPath: '/t/$slug/package'
      preLoaderRoute: typeof TSlugPackageRouteImport
      parentRoute: typeof TSlugRoute
    }
    '/t/$slug/offline-mode': {
      id: '/t/$slug/offline-mode'
      path: '/offline-mode'
      fullPath: '/t/$slug/offline-mode'
      preLoaderRoute: typeof TSlugOfflineModeRouteImport
      parentRoute: typeof TSlugRoute
    }
    '/t/$slug/notifications': {
      id: '/t/$slug/notifications'
      path: '/notifications'
      fullPath: '/t/$slug/notifications'
      preLoaderRoute: typeof TSlugNotificationsRouteImport
      parentRoute: typeof TSlugRoute
    }
    '/t/$slug/insights': {
      id: '/t/$slug/insights'
      path: '/insights'
      fullPath: '/t/$slug/insights'
      preLoaderRoute: typeof TSlugInsightsRouteImport
      parentRoute: typeof TSlugRoute
    }
    '/t/$slug/employees': {
      id: '/t/$slug/employees'
      path: '/employees'
      fullPath: '/t/$slug/employees'
      preLoaderRoute: typeof TSlugEmployeesRouteImport
      parentRoute: typeof TSlugRoute
    }
    '/t/$slug/customers': {
      id: '/t/$slug/customers'
      path: '/customers'
      fullPath: '/t/$slug/customers'
      preLoaderRoute: typeof TSlugCustomersRouteImport
      parentRoute: typeof TSlugRoute
    }
    '/t/$slug/credit-ledger': {
      id: '/t/$slug/credit-ledger'
      path: '/credit-ledger'
      fullPath: '/t/$slug/credit-ledger'
      preLoaderRoute: typeof TSlugCreditLedgerRouteImport
      parentRoute: typeof TSlugRoute
    }
    '/t/$slug/products/': {
      id: '/t/$slug/products/'
      path: '/products'
      fullPath: '/t/$slug/products/'
      preLoaderRoute: typeof TSlugProductsIndexRouteImport
      parentRoute: typeof TSlugRoute
    }
    '/t/$slug/products/$storeId': {
      id: '/t/$slug/products/$storeId'
      path: '/products/$storeId'
      fullPath: '/t/$slug/products/$storeId'
      preLoaderRoute: typeof TSlugProductsStoreIdRouteImport
      parentRoute: typeof TSlugRoute
    }
    '/t/$slug/features/$featureKey': {
      id: '/t/$slug/features/$featureKey'
      path: '/features/$featureKey'
      fullPath: '/t/$slug/features/$featureKey'
      preLoaderRoute: typeof TSlugFeaturesFeatureKeyRouteImport
      parentRoute: typeof TSlugRoute
    }
  }
}

interface TSlugRouteChildren {
  TSlugCreditLedgerRoute: typeof TSlugCreditLedgerRoute
  TSlugCustomersRoute: typeof TSlugCustomersRoute
  TSlugEmployeesRoute: typeof TSlugEmployeesRoute
  TSlugInsightsRoute: typeof TSlugInsightsRoute
  TSlugNotificationsRoute: typeof TSlugNotificationsRoute
  TSlugOfflineModeRoute: typeof TSlugOfflineModeRoute
  TSlugPackageRoute: typeof TSlugPackageRoute
  TSlugPosRoute: typeof TSlugPosRoute
  TSlugPurchaseOrdersRoute: typeof TSlugPurchaseOrdersRoute
  TSlugReceiptsRoute: typeof TSlugReceiptsRoute
  TSlugRolesPermissionsRoute: typeof TSlugRolesPermissionsRoute
  TSlugSalesRoute: typeof TSlugSalesRoute
  TSlugSettingsRoute: typeof TSlugSettingsRoute
  TSlugStoresRoute: typeof TSlugStoresRoute
  TSlugSuppliersRoute: typeof TSlugSuppliersRoute
  TSlugIndexRoute: typeof TSlugIndexRoute
  TSlugFeaturesFeatureKeyRoute: typeof TSlugFeaturesFeatureKeyRoute
  TSlugProductsStoreIdRoute: typeof TSlugProductsStoreIdRoute
  TSlugProductsIndexRoute: typeof TSlugProductsIndexRoute
}

const TSlugRouteChildren: TSlugRouteChildren = {
  TSlugCreditLedgerRoute: TSlugCreditLedgerRoute,
  TSlugCustomersRoute: TSlugCustomersRoute,
  TSlugEmployeesRoute: TSlugEmployeesRoute,
  TSlugInsightsRoute: TSlugInsightsRoute,
  TSlugNotificationsRoute: TSlugNotificationsRoute,
  TSlugOfflineModeRoute: TSlugOfflineModeRoute,
  TSlugPackageRoute: TSlugPackageRoute,
  TSlugPosRoute: TSlugPosRoute,
  TSlugPurchaseOrdersRoute: TSlugPurchaseOrdersRoute,
  TSlugReceiptsRoute: TSlugReceiptsRoute,
  TSlugRolesPermissionsRoute: TSlugRolesPermissionsRoute,
  TSlugSalesRoute: TSlugSalesRoute,
  TSlugSettingsRoute: TSlugSettingsRoute,
  TSlugStoresRoute: TSlugStoresRoute,
  TSlugSuppliersRoute: TSlugSuppliersRoute,
  TSlugIndexRoute: TSlugIndexRoute,
  TSlugFeaturesFeatureKeyRoute: TSlugFeaturesFeatureKeyRoute,
  TSlugProductsStoreIdRoute: TSlugProductsStoreIdRoute,
  TSlugProductsIndexRoute: TSlugProductsIndexRoute,
}

const TSlugRouteWithChildren = TSlugRoute._addFileChildren(TSlugRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  OnboardingRoute: OnboardingRoute,
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
  AuthSignupRoute: AuthSignupRoute,
  TSlugRoute: TSlugRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
